name: â“ Question
description: Ask a question about using Sharingan
title: "[Question]: "
labels: ["question"]
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Have a question about using Sharingan? We're here to help!

              > ðŸ’¡ **Tip:** Consider using [GitHub Discussions](https://github.com/Taiizor/Sharingan/discussions) for general questions.

    - type: dropdown
      id: topic
      attributes:
          label: Question Topic
          description: What is your question about?
          options:
              - Getting Started / Setup
              - Provider Configuration
              - Async Operations
              - Multi-Process Safety
              - Encryption
              - Dependency Injection
              - Configuration Bridge
              - Migration from other libraries
              - Performance
              - Cross-Platform Behavior
              - Other
      validations:
          required: true

    - type: textarea
      id: question
      attributes:
          label: Your Question
          description: What would you like to know?
      validations:
          required: true

    - type: textarea
      id: context
      attributes:
          label: Context
          description: Provide any relevant context, code samples, or what you've already tried.
          render: csharp
      validations:
          required: false

    - type: dropdown
      id: target-framework
      attributes:
          label: Target Framework (if applicable)
          description: Which target framework are you using?
          options:
              - Not applicable
              - .NET Framework 4.8
              - .NET Framework 4.8.1
              - .NET Standard 2.0
              - .NET Standard 2.1
              - .NET 7.0
              - .NET 8.0
              - .NET 9.0
              - .NET 10.0
      validations:
          required: false

    - type: dropdown
      id: platform
      attributes:
          label: Platform (if applicable)
          description: Which platform are you running on?
          options:
              - Not applicable
              - Windows
              - Linux
              - macOS
              - Android
              - iOS
      validations:
          required: false
